spring.application.name=EgregoreBot

discord.token=${DISCORD_BOT_TOKEN}

# Configuración de Logs (para ver qué pasa)
logging.level.net.dv8tion.jda=INFO

# --- Configuración de Base de Datos (H2) ---
# Esto crea un archivo llamado "egregore_db" en tu carpeta de usuario
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Habilita la consola web para que puedas ver los datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA: Crea las tablas automáticamente basado en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect